### PR TITLE
fix: bulkWriter: ensure buffered batches are sent after flush

### LINKED ISSUE #1531: BulkWriter.close doesn't resolve when writing more than 500 documents
## Environment details
  - OS: GCP
  - Node.js version: 14
  - npm version: 6.14.13
  - `@google-cloud/firestore` version: 4.12.2

## Steps to reproduce
We started seeing weird timeouts in our production environment from functions that use BulkWriter when we updated from v4.9.4 to v.4.12.2. We believe the bug was introduced in v.4.10.0, and specifically in #1470 , but we haven't been able to find the cause.

To reproduce it we wrote a very simple function:
```
const admin = require('firebase-admin');
const functions = require('firebase-functions');

const db = admin.firestore();

module.exports = functions.https.onCall(async (data, context) => {
  const { count } = data;
  const bulkWriter = db.bulkWriter();
  console.info(`Writing ${count} documents`);
  for (let i = 0; i < count; i++) {
    bulkWriter.set(db.collection('bulkWriter').doc(i.toString()), { id: i });
  }
  console.info('Awaiting close');
  await bulkWriter.close();
  console.info('done');
});
```
and then we tested it using different firestore versions, with the following logs in each case:
#### Call with count: 500
```
2021-06-09 16:08:53.145 CLT toolsBulkWriter d9td8maqfes7 Function execution started
Info 2021-06-09 16:08:53.151 CLT toolsBulkWriter d9td8maqfes7 Writing 500 documents
Info 2021-06-09 16:08:53.173 CLT toolsBulkWriter d9td8maqfes7 Awaiting close
Info 2021-06-09 16:08:53.308 CLT toolsBulkWriter d9td8maqfes7 done
Debug 2021-06-09 16:08:53.309 CLT toolsBulkWriter d9td8maqfes7 Function execution took 164 ms, finished with status code: 200
```
#### Call with count: 501
```
Debug 2021-06-09 16:08:58.514 CLT toolsBulkWriter d9tdldqqzztb Function execution started
Info 2021-06-09 16:08:58.523 CLT toolsBulkWriter d9tdldqqzztb Writing 501 documents
Info 2021-06-09 16:08:58.617 CLT toolsBulkWriter d9tdldqqzztb Awaiting close
Info 2021-06-09 16:08:58.836 CLT toolsBulkWriter d9tdldqqzztb done
Debug 2021-06-09 16:08:58.837 CLT toolsBulkWriter d9tdldqqzztb Function execution took 324 ms, finished with status code: 200
```
Works as expected, maybe the additional document is adding too much additional time but it's not worrysome.
#### Call with count: 500
```
Debug 2021-06-09 15:20:46.599 CLT toolsBulkWriter i03lzixmk8hj Function execution started
Info 2021-06-09 15:20:46.639 CLT toolsBulkWriter i03lzixmk8hj Writing 500 documents
Info 2021-06-09 15:20:46.679 CLT toolsBulkWriter i03lzixmk8hj Awaiting close
Debug 2021-06-09 15:20:47.355 CLT toolsBulkWriter i03lzixmk8hj Function execution took 757 ms, finished with status code: 200
Info 2021-06-09 15:20:47.372 CLT toolsBulkWriter i03lzixmk8hj done
```
#### Call with count: 501
```
Debug 2021-06-09 15:20:53.337 CLT toolsBulkWriter i03lphytcqlt Function execution started
Info 2021-06-09 15:20:53.354 CLT toolsBulkWriter i03lphytcqlt Writing 501 documents
Info 2021-06-09 15:20:53.380 CLT toolsBulkWriter i03lphytcqlt Awaiting close
Debug 2021-06-09 15:29:53.339 CLT toolsBulkWriter i03lphytcqlt Function execution took 540002 ms, finished with status: 'timeout'
```
With 501 documents it doesn't finish. Note that we increased the function timeout to the maximum (540s).
#### Call with count: 500
```
2021-06-09 15:42:02.637 CLT toolsBulkWriter 0a53aoh0s0dq Function execution started
Info 2021-06-09 15:42:02.700 CLT toolsBulkWriter 0a53aoh0s0dq Writing 500 documents
Info 2021-06-09 15:42:02.728 CLT toolsBulkWriter 0a53aoh0s0dq Awaiting close
Info 2021-06-09 15:42:02.895 CLT toolsBulkWriter 0a53aoh0s0dq done
Debug 2021-06-09 15:42:02.897 CLT toolsBulkWriter 0a53aoh0s0dq Function execution took 260 ms, finished with status code: 200
```
#### Call with count: 501
```
Debug 2021-06-09 15:42:09.447 CLT toolsBulkWriter 0a539qoiqna9 Function execution started
Info 2021-06-09 15:42:09.501 CLT toolsBulkWriter 0a539qoiqna9 Writing 501 documents
Info 2021-06-09 15:42:09.530 CLT toolsBulkWriter 0a539qoiqna9 Awaiting close
2021-06-09 15:51:09.449 CLT toolsBulkWriter 0a539qoiqna9 Function execution took 540003 ms, finished with status: 'timeout'
```
As you can see, the issue remains in the most recent version.

Note that we also tested in the emulator, but we don't see this behavior.

Thanks!

### PR DESCRIPTION
**Pull request by thebrianchen**
Fixes #1531.

`flush()` currently does not schedule batches that are buffered, which caused the issue above. If the last batch did not meet the maximum batch size, it would not be sent, causing `flush()` to never resolve.

This PR allows BulkWriter to track when `flush()` is called while there are buffered operations and ensures that the batch is flushed even if it is not at the maximum batch size. I'm not a huge fan of adding the `BufferedOperation`, class but I can't seem to find a clean way to do it. Added a unit test that fails without this logic.

### CODE REVIEW

File: dev/src/bulk-writer.ts [hunk 1]
```diff
@@ -271,6 +282,18 @@ class BulkCommitBatch extends WriteBatch {
   }
 }
 
+/**
+ * Used to represent a buffered BulkWriterOperation.
+ *
+ * @private
+ */
+class BufferedOperation {
```
Comment (schmidt-sebastian) [inline dev/src/bulk-writer.ts:290]: Can you just enqueue BulkWriterOperation and make send() public?

**Review by schmidt-sebastian — APPROVED** [review]
Tried to come up with a better way but failed. See if you can address my comment. If not, this is fine as is. Please remember to cut a release.

File: dev/src/bulk-writer.ts (hunk 1 above)
Comment (thebrianchen) [reply dev/src/bulk-writer.ts:290]: I tried that approach, but that requires storing `enqueueOnBatchCallback` onto `BulkWriterOperation`, which doesn't make sense conceptually.
