### PR TITLE
fix: wait for operations to complete before deleting clients

### LINKED ISSUE #913: Closing an onSnapshot listener gives UnhandledPromiseRejectionWarnings when followed by client.terminate()
#### Environment details

  - OS: macOS Catalina (`10.15.1`)
  - Node.js version: `10.16.3`
  - npm version: `6.9.0`
  - `@google-cloud/firestore` version: `^3.4.1`

#### Problem

When closing an onSnapshot listener, followed by the termination of the firestore client, an 'UnhandledPromiseRejectionWarning' is shown:

```
onSnapshot { path: 'collection/doc-1', exists: false }
onSnapshot { path: 'collection/doc-1', exists: true }
(node:41140) UnhandledPromiseRejectionWarning: AssertionError [ERR_ASSERTION]: No active request
    at ClientPool.release (/Users/vdvleon/Downloads/reproduction/node_modules/@google-cloud/firestore/build/src/pool.js:95:9)
    at op.catch.then (/Users/vdvleon/Downloads/reproduction/node_modules/@google-cloud/firestore/build/src/pool.js:162:24)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:41140) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:41140) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

#### Steps to reproduce

1. Open an onSnapshot listener (on either documents or queries) and store the 'close' callback.
   `const close = documentReference.onSnapshot(...);`
2. Call the 'close' callback.
   `close();`
3. Terminate the firestore client.
    `firestore.terminate();`

_Relevant code:_
```typescript
const documentReference = firestore.collection("collection").doc("doc-1");

const close = documentReference.onSnapshot((snapshot: DocumentSnapshot) => {
  console.log("onSnapshot", {
    path: snapshot.ref.path,
    exists: snapshot.exists
  });
});

const run = async (): Promise<void> => {
  await clearFirestoreData();

  await documentReference.set({});

  close();

  await firestore.terminate();
};
```

_The full reproduction can be found here:_
[reproduction.zip](https://github.com/googleapis/nodejs-firestore/files/4158731/reproduction.zip)

**To run the code:**

```bash
cd reproduction
npm install
npx ts-node index.ts
```

### PR DESCRIPTION
**Pull request by thebrianchen**
Fixes #913 

Implemented the 2nd suggestion. I think it makes more sense to allow for existing operations to complete before calling terminate. In the user's repro it would be strange to have `close()` throw an error.

### CODE REVIEW

File: dev/src/pool.ts [hunk 1]
```diff
@@ -112,8 +118,12 @@ export class ClientPool<T> {
    */
   private async release(requestTag: string, client: T): Promise<void> {
     const requestCount = this.activeClients.get(client) || 0;
-    assert(requestCount > 0, 'No active request');
+    assert(
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: Nit: I like the previous version better cause it is one line instead of 4.

File: dev/src/pool.ts [hunk 2]
```diff
@@ -112,8 +118,12 @@ export class ClientPool<T> {
...
+      requestCount > 0,
+      'Release failed. No active requests are on the client.'
+    );
     this.activeClients.set(client, requestCount - 1);
+    this.operationsDeferred.resolve();
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: `release()` gets called after every request. It does not mean that no clients have pending operations. If you want to keep `operationsDeferred`, I think you need logic here to determine whether there are any operations left.

File: dev/src/pool.ts [hunk 3]
```diff
@@ -195,6 +205,14 @@ export class ClientPool<T> {
 
   async terminate(): Promise<void> {
     this.terminated = true;
+
+    // If there are any operations still running after terminate() is called,
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: I think this only thing you have to do here is set `maxIdleClients` to 0 and call `shouldGarbageCollectClient()`.

It will remove the remaining client if it  is currently idle. If not, the next run of `shouldGarbageCollectClient()` will trigger the removal (which should happen after `release()`)

File: dev/system-test/firestore.ts [hunk 4]
```diff
@@ -992,6 +992,19 @@ describe('DocumentReference class', () => {
...
+      const ref = randomCol.doc('doc-1');
+
+      const unsubscribe = ref.onSnapshot(() => {
+        // No-op
+      });
+
+      await ref.set({});
+      unsubscribe();
+      // Terminate should allow unsubscribe to complete.
+      await firestore.terminate();
```
Comment (schmidt-sebastian) [inline dev/system-test/firestore.ts]: I think this test won't actually fail in the current client, it will just log a rejected Promise warning. We might be better off adding this as a unit test to the ClientPool unit tests.

**Comment by schmidt-sebastian** [comment]
> Do I read it correctly, that after resolving the Promise returned by `terminate()`, there might be still some actions pending? This is not an expected behavior, as it would again break some of the use cases for which this method was introduced in the first place. A correct behavior would be to wait for all of the pending operations to complete before resolving `terminate()`.

We are debating between letting terminate() "hang" until all listeners are disconnected or terminating all active listeners with errors. Having user feedback here would be valuable.

**Comment by merlinnot** [comment]
In the original report you can see that listeners are actually disconnected before `terminate` is called. It's just that disconnecting the listener is exposed as a synchronous operation, whereas it's actually not.

I'd say that ideally disconnect of a listener should in that case also return a Promise, so you can shut down everything gracefully.

If this API change is not acceptable, what I'd expect is:
- When listeners were disconnected (synchronously) before calling `terminate()`, wait for all of the background operations to complete before resolving the Promise.
- When some of the listeners were not disconnected (synchronously) before calling `terminate()`, return a rejected Promise along the lines of "All listeners must be disconnected before terminating the client.".

Why? Because if you forget to disconnect some listeners and wait for `terminate()`, it will never resolve and debugging this issue might be hard. If you, on the other hand, terminate listeners with errors, you don't give developers a chance to shutdown the client gracefully.

**Comment by schmidt-sebastian** [comment]
@thebrianchen What @merlinnot suggested sounds sane to me. So, on `terminate()` we error if there are any active listeners. If there are no active listens, we block until all other operations complete (including listener disconnects, RunQuery processing and any outstanding writes).

File: dev/src/index.ts [hunk 5]
```diff
@@ -298,6 +298,13 @@ export class Firestore {
    */
   private _projectId: string | undefined = undefined;
 
+  /**
+   * Set of requestTags associated with the listeners that have been registered
+   * on the client.
+   * @private
+   */
+  private registeredListeners = new Set<string>();
```
Comment (schmidt-sebastian) [inline dev/src/index.ts]: I think you only need a counter. Requests tags are also not guaranteed to be unique, since the generator just uses whatever `rand()` implementation the system exposes.

File: dev/src/index.ts [hunk 6]
```diff
@@ -987,12 +994,39 @@ export class Firestore {
...
   }
 
+  /**
+   * Registers the requestTag associated with the listener. This is used to
+   * ensure that all listeners are detached when terminate() is called.
+   *
+   * @private
+   * @param requestTag A unique client-assigned identifier
+   */
+  registerListener(requestTag: string): void {
```
Comment (schmidt-sebastian) [inline dev/src/index.ts]: It would be nice if this was somehow scoped to the class itself, but I can't find a good way to do this. `readStream` would be a natural place, but it would allow stream retries after the client is terminated.

File: dev/src/pool.ts [hunk 7]
```diff
@@ -42,6 +42,12 @@ export class ClientPool<T> {
    */
   private terminated = false;
 
+  /**
+   * Deferred promise that is resolved when there are no active operations on
+   * the client pool.
+   */
+  private operationsDeferred = new Deferred<void>();
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: Can you come up with a more descriptive name?

File: dev/src/watch.ts [hunk 8]
```diff
@@ -252,7 +252,8 @@ abstract class Watch<T = DocumentData> {
 
     this.initStream();
 
-    return () => {
+    const unsubscribe = () => {
+      this.firestore.unregisterListener(this.requestTag);
```
Comment (schmidt-sebastian) [inline dev/src/watch.ts]: I don't think this is the only place that Listens are terminated. What happens if we throw an error and terminate from our end?

File: dev/src/pool.ts [hunk 9]
```diff
@@ -195,6 +204,12 @@ export class ClientPool<T> {
 
   async terminate(): Promise<void> {
     this.terminated = true;
+
+    // Wait for all pending operations to complete before terminating.
+    if (this.opCount > 0) {
+      this.operationsDeferred = new Deferred<void>();
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: It would help to have a log line here.

File: dev/system-test/firestore.ts [hunk 10]
```diff
@@ -152,6 +152,25 @@ describe('Firestore class', () => {
...
+    await ref.set({});
+    try {
+      await firestore.terminate();
+      return Promise.reject('terminate() should have failed');
+    } catch (err) {
+      expect(err).to.equal(
+        'All listeners must be disconnected before terminating the client.'
+      );
+      unsubscribe();
+      return Promise.resolve();
```
Comment (schmidt-sebastian) [inline dev/system-test/firestore.ts]: This line is not needed.

File: dev/system-test/firestore.ts [hunk 11]
```diff
@@ -152,6 +152,25 @@ describe('Firestore class', () => {
...
+  it('throws an error if terminate() is called with active listeners', async () => {
+    const ref = randomCol.doc('doc-1');
+    const unsubscribe = ref.onSnapshot(() => {
+      // No-op
+    });
+
+    await ref.set({});
+    try {
+      await firestore.terminate();
+      return Promise.reject('terminate() should have failed');
```
Comment (schmidt-sebastian) [inline dev/system-test/firestore.ts]: Nit: Would prefer if you just threw an exception here. It's better not to mix Promises and async/await when possible.

File: dev/test/pool.ts [hunk 12]
```diff
@@ -327,4 +327,25 @@ describe('Client pool', () => {
...
+
+  it('waits for existing operations to complete before releasing clients', async () => {
+    const clientPool = new ClientPool<{}>(1, 0, () => {
+      return {};
+    });
+    const deferred = new Deferred<void>();
+
+    const op = clientPool.run(REQUEST_TAG, async () => {
+      await deferred.promise;
+      return Promise.resolve('success');
```
Comment (schmidt-sebastian) [inline dev/test/pool.ts]: You can just return `deferred.promise`.

File: dev/test/pool.ts [hunk 13]
```diff
@@ -327,4 +327,25 @@ describe('Client pool', () => {
...
+    });
+    const terminate = clientPool
+      .terminate()
+      .then(() => Promise.resolve('success'));
```
Comment (schmidt-sebastian) [inline dev/test/pool.ts]: You don't need to return a resolved Promise here, but you could use the `then` callback to modify some global state. That allows you to verify that it hasn't run:

```
let terminated = false;

const terminateOp = clientPool.terminate(() => { terminate = true });

// Give the Promise chain a chance to resolve

setImmediate(() => {
   expect(terminate).to.be.false;
   
   await terminateOp;
   expect(terminated).to.be.true;
   done(); // New done() callback
});

```

File: dev/test/pool.ts [hunk 14]
```diff
@@ -327,4 +327,25 @@ describe('Client pool', () => {
...
+    deferred.resolve();
+
+    // Wait for the terminate promise to resolve after run() completes.
+    await terminate;
+    expect(op).to.become('success');
```
Comment (schmidt-sebastian) [inline dev/test/pool.ts]: If you keep this, I think you need to call `await` since `become` is a PromisedAssertion.

File: dev/test/pool.ts (hunk 13 above)
Comment (thebrianchen) [reply dev/test/pool.ts]: This is very clean, thanks!

File: dev/src/pool.ts (hunk 7 above)
Comment (thebrianchen) [reply dev/src/pool.ts]: there are no names I could come up with that sound good: operationsFinishedDeferred, operationsCompletedDeferred, allRequestsCompleted, ready4terminatedeferred

File: dev/src/watch.ts (hunk 8 above)
Comment (thebrianchen) [reply dev/src/watch.ts]: `this.isActive` is only set here and in `closeStream()` (not counting constructor initialization). Added an unregister call in both places iff `isActive` is set to true.

File: dev/src/index.ts (hunk 6 above)
Comment (thebrianchen) [reply dev/src/index.ts]: I spent a chunk of time thinking about this last week, and I couldn't think of a way to pipe it through another way. 
 - `ClientPool` is charge of terminating the client.
 - It seems like the only place to accurately track listeners w/o having to deal with extra node stream logic is to monitor each listener registration in watch.
- `Firestore` is the only place to store the Watch information.

File: dev/src/index.ts [hunk 15]
```diff
@@ -298,6 +298,13 @@ export class Firestore {
    */
   private _projectId: string | undefined = undefined;
 
+  /**
+   * Set of requestTags associated with the listeners that have been registered
+   * on the client.
+   * @private
```
Comment (schmidt-sebastian) [inline dev/src/index.ts]: Please update JSDoc.

File: dev/src/index.ts [hunk 16]
```diff
@@ -987,12 +994,39 @@ export class Firestore {
...
   }
 
+  /**
+   * Registers the requestTag associated with the listener. This is used to
+   * ensure that all listeners are detached when terminate() is called.
+   *
+   * @private
+   * @param requestTag A unique client-assigned identifier
+   */
+  registerListener(): void {
```
Comment (schmidt-sebastian) [inline dev/src/index.ts]: Please update JSDoc.

File: dev/src/index.ts [hunk 17]
```diff
@@ -987,12 +994,39 @@ export class Firestore {
...
+  }
+
+  /**
+   * Unregisters the requestTag associated with the listener. This is used to
+   * ensure that all listeners are detached when terminate() is called.
+   *
+   * @private
+   * @param requestTag A unique client-assigned identifier
+   */
+  unregisterListener(): void {
```
Comment (schmidt-sebastian) [inline dev/src/index.ts]: Please update JSDoc.

File: dev/src/index.ts [hunk 18]
```diff
@@ -987,12 +994,39 @@ export class Firestore {
...
+
   /**
    * Terminates the Firestore client and closes all open streams.
    *
    * @return A Promise that resolves when the client is terminated.
    */
   terminate(): Promise<void> {
+    if (this.registeredListenersCount > 0) {
+      return Promise.reject(
+        'All listeners must be disconnected before terminating the client.'
```
Comment (schmidt-sebastian) [inline dev/src/index.ts]: Please use the terms we use in our API: "onSnapshot() listeners" and "unsubscribe".

File: dev/src/pool.ts [hunk 19]
```diff
@@ -42,6 +42,12 @@ export class ClientPool<T> {
    */
   private terminated = false;
 
+  /**
+   * Deferred promise that is resolved when there are no active operations on
+   * the client pool.
+   */
+  private operationsCompletedDeferred = new Deferred<void>();
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: Ideally, we would also block new tasks from submission. We could then use a single boolean ("terminatePending") and a deferred Promise ("terminateDeferred"), which might make this code a bit cleaner. "Operations Completed" is a state that happens all the time, but it is only relevant during shutdown.

File: dev/src/pool.ts [hunk 20]
```diff
@@ -195,6 +204,17 @@ export class ClientPool<T> {
...
   async terminate(): Promise<void> {
     this.terminated = true;
+
+    // Wait for all pending operations to complete before terminating.
+    if (this.opCount > 0) {
+      this.operationsCompletedDeferred = new Deferred<void>();
+      logger(
+        'ClientPool.terminate',
+        /* requestTag= */ null,
+        'Waiting for all pending operations to complete before terminating'
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: Nit: Instead of "all", you could log the number of operations.

File: dev/system-test/firestore.ts [hunk 21]
```diff
@@ -152,6 +152,24 @@ describe('Firestore class', () => {
...
       });
   });
+
+  it('throws an error if terminate() is called with active listeners', async () => {
+    const ref = randomCol.doc('doc-1');
+    const unsubscribe = ref.onSnapshot(() => {
+      // No-op
+    });
+
+    await ref.set({});
```
Comment (schmidt-sebastian) [inline dev/system-test/firestore.ts]: This line can be dropped.

File: dev/system-test/firestore.ts [hunk 22]
```diff
@@ -152,6 +152,24 @@ describe('Firestore class', () => {
...
+    try {
+      await firestore.terminate();
+      throw new Error('terminate() should have failed');
+    } catch (err) {
+      expect(err).to.equal(
+        'All listeners must be disconnected before terminating the client.'
+      );
+      unsubscribe();
+    }
```
Comment (schmidt-sebastian) [inline dev/system-test/firestore.ts]: Nit: If you want, you can simplify this as such: https://github.com/googleapis/nodejs-firestore/blob/7562033876dc006e77d00b576b2541a7dfd30c66/dev/test/transaction.ts#L408

File: dev/test/pool.ts [hunk 23]
```diff
@@ -327,4 +327,29 @@ describe('Client pool', () => {
...
+
+    // Run operation that completes after terminate() is called.
+    clientPool.run(REQUEST_TAG, () => {
+      return deferred.promise;
+    });
+    const terminateOp = clientPool.terminate().then(() => {
+      terminated = true;
+    });
+
+    setImmediate(async () => {
```
Comment (schmidt-sebastian) [inline dev/test/pool.ts]: Just glancing at this, I don't quite follow why we need `setImmediate`. Can you add a comment (or remove it if it isn't necessary).

File: dev/src/pool.ts (hunk 19 above)
Comment (thebrianchen) [reply dev/src/pool.ts]: The `terminated` boolean already blocks new tasks from submission after terminate() is called. Renamed to `terminateDeferred`

File: dev/src/index.ts [hunk 24]
```diff
@@ -995,22 +995,22 @@ export class Firestore {
   }
 
   /**
-   * Registers the requestTag associated with the listener. This is used to
-   * ensure that all listeners are detached when terminate() is called.
+   * Registers a listener on this client, incrementing the listener count. This
+   * is used to ensure that all listeners are unsubscribed when terminate() is
```
Comment (schmidt-sebastian) [inline dev/src/index.ts]: s/ensure/assert (or verify?). Here and below.

File: dev/src/pool.ts [hunk 25]
```diff
@@ -121,7 +121,7 @@ export class ClientPool<T> {
     assert(requestCount > 0, 'No active requests');
     this.activeClients.set(client, requestCount - 1);
     if (this.opCount === 0) {
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: Suggestion: `if (terminated && this.opCount == 0)`

File: dev/src/pool.ts [hunk 26]
```diff
@@ -207,13 +207,14 @@ export class ClientPool<T> {
 
     // Wait for all pending operations to complete before terminating.
     if (this.opCount > 0) {
-      this.operationsCompletedDeferred = new Deferred<void>();
+      this.terminateDeferred = new Deferred<void>();
```
Comment (schmidt-sebastian) [inline dev/src/pool.ts]: If you apply the previous suggestion, this line can be removed. You may want to update the comment in line 45 as well.

File: dev/src/index.ts (hunk 15 above)
Comment (schmidt-sebastian) [reply dev/src/index.ts]: I think you missed this comment.

Comment (thebrianchen) [reply dev/src/index.ts]: oops

File: dev/src/pool.ts (hunk 26 above)
Comment (thebrianchen) [reply dev/src/pool.ts]: removed here and added comment above to include that terminate() has to be called.
