### PR TITLE
fix!: Update WithFieldData and PartialWithFieldData to ignore methods on types

### LINKED ISSUE #2291: WithFieldValue mangles Class Types
### Please make sure you have searched for information in the following guides.

- [x] Search the issues already opened: https://github.com/GoogleCloudPlatform/google-cloud-node/issues
- [x] Search StackOverflow: http://stackoverflow.com/questions/tagged/google-cloud-platform+node.js
- [x] Check our Troubleshooting guide: https://github.com/googleapis/google-cloud-node/blob/main/docs/troubleshooting.md
- [x] Check our FAQ: https://github.com/googleapis/google-cloud-node/blob/main/docs/faq.md
- [x] Check our libraries HOW-TO: https://github.com/googleapis/gax-nodejs/blob/main/client-libraries.md
- [x] Check out our authentication guide: https://github.com/googleapis/google-auth-library-nodejs
- [x] Check out handwritten samples for many of our APIs: https://github.com/GoogleCloudPlatform/nodejs-docs-samples

### A screenshot that you have tested with "Try this API".

Attempting to use `WithFieldValue<Date>` mangles to `Date` type such that `tsc` no longer recognizes it as a Date. I assume this happens for most other non-primitive values in Firestore documents.

```
   63:37  error   Argument of type 'FieldValue | WithFieldValue<Date>' is not assignable to parameter of type 'Date | FieldValue'. ​typescript(2345)
                    Type '{ toString: FieldValue | WithFieldValue<() => string>; toDateString: FieldValue | WithFieldValue<() => string>; toTimeString: FieldValue | WithFieldValue<...>; ... 41 more ...; [Symbol.toPrimitive]: FieldValue | WithFieldValue<...>; }' is not assignable to type 'Date | FieldValue'.
                      Type '{ toString: FieldValue | WithFieldValue<() => string>; toDateString: FieldValue | WithFieldValue<() => string>; toTimeString: FieldValue | WithFieldValue<...>; ... 41 more ...; [Symbol.toPrimitive]: FieldValue | WithFieldValue<...>; }' is not assignable to type 'Date'.
                        Types of property 'toString' are incompatible.
                          Type 'FieldValue | WithFieldValue<() => string>' is not assignable to type '() => string'.
                            Type 'FieldValue' is not assignable to type '() => string'.
                              Type 'FieldValue' provides no match for the signature '(): string'.
```

### Link to repro. A link to a **public** Github Repository or gist with a minimal reproduction.

https://github.com/rgant/brainfry

https://gist.github.com/rgant/adf3984ebd43c278b716c372412f7109/193be3d9e79f8beafc452a2c814af61883ea9958

### A step-by-step description of how to reproduce the issue, based on the linked reproduction.

This all happens when running linters and type checkers in my editor.

### A clear and concise description of what the bug is, and what you expected to happen.

Because `WithFieldValue<Post>` climbs inside of the `Date` property this results problems with typing as seen on [line 63](https://gist.github.com/rgant/adf3984ebd43c278b716c372412f7109/193be3d9e79f8beafc452a2c814af61883ea9958#file-post-ts-L63)

I can [fix](https://gist.github.com/rgant/adf3984ebd43c278b716c372412f7109#file-post-ts-L77) this (with some ugly unnecessary code my throwing a `TypeError` if the parameter isn't a `Date` nor a `FieldValue`.

### A clear and concise description WHY you expect this behavior, i.e., was it a recent change, there is documentation that points to this behavior, etc. **

I feel like the [documentation update is better](https://github.com/googleapis/nodejs-firestore/pull/1958), but doesn't actually cover a real world case. Maybe I'm just strange but I wouldn't use a number of milliseconds in a front end application where I expect to display a date and time of a post. I would use a JavaScript `Date` (or [`Temporal`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Temporal)).

### PR DESCRIPTION
**Pull request by MarkDuckworth**
Partially fixes googleapis/nodejs-firestore#2291 - Will not affect methods on types passed to WithFieldData and PartialWithFieldData.

This has some potential to be a breaking change, so I have marked it as such. To be safe, I will include it in the next major version release.

### CODE REVIEW

File: dev/test/gapic_firestore_v1.ts [hunk 1]
```diff
@@ -482,7 +482,9 @@ describe('v1.FirestoreClient', () => {
         ['document', 'name']
       );
       request.document.name = defaultValue1;
-      const expectedHeaderRequestParams = `document.name=${defaultValue1 ?? ''}`;
+      const expectedHeaderRequestParams = `document.name=${
```
Comment (milaGGL) [inline dev/test/gapic_firestore_v1.ts:485]: I assume the changes in these 3 files are all format changes, correct?

**Review by milaGGL — APPROVED** [review]
LGTM

File: dev/test/gapic_firestore_v1.ts (hunk 1 above)
Comment (MarkDuckworth) [reply dev/test/gapic_firestore_v1.ts]: correct. good question

**Comment by VictorLeach96** [comment]
Does this affect https://github.com/googleapis/nodejs-firestore/issues/1890 at all?
